export const cardArray = [
  {
    id: 0,
    title: "Пвх материал 1й сорт",
    price: "170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-image.png",
  },
  {
    id: 1,
    title: "Пвх материал 2й сорт",
    price: "270 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-image.png",
  },
  {
    id: 2,
    title: "Пвх материал 3й сорт",
    price: "370 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-image.png",
  },
  {
    id: 3,
    title: "Пвх материал 4й сорт",
    price: "470 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-image.png",
  },
  {
    id: 4,
    title: "Пвх материал 5й сорт",
    price: "570 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-image.png",
  },
  {
    id: 5,
    title: "Пвх материал 6й сорт",
    price: "670 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/image/card-image.png",
  },
];
